# Form implementation generated from reading ui file 'ui/qt/launch_screen.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LaunchScreen(object):
    def setupUi(self, LaunchScreen):
        LaunchScreen.setObjectName("LaunchScreen")
        LaunchScreen.resize(450, 300)
        LaunchScreen.setMinimumSize(QtCore.QSize(450, 300))
        LaunchScreen.setMaximumSize(QtCore.QSize(450, 300))
        LaunchScreen.setStyleSheet("QWidget{\n"
"    background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(0, 102, 153, 69), stop:0.375 rgba(0, 102, 153, 69), stop:0.423533 rgba(0, 102, 153, 145), stop:0.45 rgba(0, 102, 153, 208), stop:0.477581 rgba(0, 102, 153, 130), stop:0.518717 rgba(0, 102, 153, 130), stop:0.55 rgba(0, 102, 153, 255), stop:0.57754 rgba(0, 102, 153, 130), stop:0.625 rgba(0, 102, 153, 69), stop:1 rgba(0, 102, 153, 69));\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 159, 10);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgba(255, 159, 10, 0.8);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=LaunchScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_new_game = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_new_game.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_new_game.setObjectName("pushButton_new_game")
        self.gridLayout.addWidget(self.pushButton_new_game, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 2, 1)
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(140, 0))
        self.pushButton_exit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        LaunchScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LaunchScreen)
        QtCore.QMetaObject.connectSlotsByName(LaunchScreen)

    def retranslateUi(self, LaunchScreen):
        _translate = QtCore.QCoreApplication.translate
        LaunchScreen.setWindowTitle(_translate("LaunchScreen", "Числовая угадайка"))
        self.pushButton_new_game.setText(_translate("LaunchScreen", "Новая игра"))
        self.pushButton_exit.setText(_translate("LaunchScreen", "Выход"))
